/* Generated By:JavaCC: Do not edit this line. GoConstants.java */

/** 
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface GoConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int WHITESPACE = 5;
  /** RegularExpression Id. */
  int SINGLE_LINE_COMMENT = 6;
  /** RegularExpression Id. */
  int MULTI_LINE_COMMENT = 7;
  /** RegularExpression Id. */
  int ID = 8;
  /** RegularExpression Id. */
  int NUM_DEC = 9;
  /** RegularExpression Id. */
  int KEYWORD = 10;
  /** RegularExpression Id. */
  int OPERATOR = 11;
  /** RegularExpression Id. */
  int DELIMITER = 12;
  /** RegularExpression Id. */
  int STRING = 13;
  /** RegularExpression Id. */
  int DIGIT = 14;
  /** RegularExpression Id. */
  int LETTER = 15;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "<WHITESPACE>",
    "<SINGLE_LINE_COMMENT>",
    "<MULTI_LINE_COMMENT>",
    "<ID>",
    "<NUM_DEC>",
    "<KEYWORD>",
    "<OPERATOR>",
    "<DELIMITER>",
    "<STRING>",
    "<DIGIT>",
    "<LETTER>",
  };

}
