/* Generated By:JavaCC: Do not edit this line. GoTokenManager.java */

/** Token Manager. */
public class GoTokenManager implements GoConstants
{

  /** Debug output. */
  public static  java.io.PrintStream debugStream = System.out;
  /** Set debug output. */
  public static  void setDebugStream(java.io.PrintStream ds) { debugStream = ds; }
private static final int jjStopStringLiteralDfa_0(int pos, long active0)
{
   switch (pos)
   {
      default :
         return -1;
   }
}
private static final int jjStartNfa_0(int pos, long active0)
{
   return jjMoveNfa_0(jjStopStringLiteralDfa_0(pos, active0), pos + 1);
}
static private int jjStopAtPos(int pos, int kind)
{
   jjmatchedKind = kind;
   jjmatchedPos = pos;
   return pos + 1;
}
static private int jjStartNfaWithStates_0(int pos, int kind, int state)
{
   jjmatchedKind = kind;
   jjmatchedPos = pos;
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) { return pos + 1; }
   return jjMoveNfa_0(state, pos + 1);
}
static private int jjMoveStringLiteralDfa0_0()
{
   switch(curChar)
   {
      case 9:
         return jjStartNfaWithStates_0(0, 2, 0);
      case 10:
         return jjStartNfaWithStates_0(0, 3, 37);
      case 13:
         return jjStartNfaWithStates_0(0, 4, 0);
      case 32:
         return jjStartNfaWithStates_0(0, 1, 0);
      default :
         return jjMoveNfa_0(5, 0);
   }
}
static final long[] jjbitVec0 = {
   0x0L, 0x0L, 0x0L, 0x8000000000000000L
};
static final long[] jjbitVec1 = {
   0x0L, 0x0L, 0xffffffffffffffffL, 0xffffffffffffffffL
};
static final long[] jjbitVec2 = {
   0xfffffffffffffffeL, 0xffffffffffffffffL, 0xffffffffffffffffL, 0xffffffffffffffffL
};
static private int jjMoveNfa_0(int startState, int curPos)
{
   //int[] nextStates; // not used
   int startsAt = 0;
   jjnewStateCnt = 271;
   int i = 1;
   jjstateSet[0] = startState;
   //int j; // not used
   int kind = 0x7fffffff;
   for (;;)
   {
      if (++jjround == 0x7fffffff)
         ReInitRounds();
      if (curChar < 64)
      {
         long l = 1L << curChar;
         do
         {
            switch(jjstateSet[--i])
            {
               case 5:
                  if ((0x7400ac6200000000L & l) != 0L)
                  {
                     if (kind > 18)
                        kind = 18;
                  }
                  else if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddStates(0, 11);
                  else if ((0x800530000000000L & l) != 0L)
                  {
                     if (kind > 19)
                        kind = 19;
                  }
                  else if ((0x100002600L & l) != 0L)
                  {
                     if (kind > 5)
                        kind = 5;
                     jjCheckNAdd(0);
                  }
                  else if ((0x7L & l) != 0L)
                  {
                     if (kind > 24)
                        kind = 24;
                  }
                  else if (curChar == 34)
                     jjCheckNAddStates(12, 15);
                  else if (curChar == 39)
                     jjAddStates(16, 21);
                  if ((0x3fe000000000000L & l) != 0L)
                  {
                     if (kind > 9)
                        kind = 9;
                     jjCheckNAddStates(22, 25);
                  }
                  else if (curChar == 46)
                     jjAddStates(26, 27);
                  else if (curChar == 48)
                  {
                     if (kind > 9)
                        kind = 9;
                     jjCheckNAddStates(28, 37);
                  }
                  else if (curChar == 47)
                     jjCheckNAddStates(38, 40);
                  else if (curChar == 45)
                     jjCheckNAddTwoStates(27, 52);
                  else if (curChar == 43)
                     jjCheckNAddTwoStates(27, 63);
                  else if (curChar == 38)
                     jjCheckNAddStates(41, 44);
                  else if (curChar == 62)
                     jjCheckNAddStates(45, 47);
                  else if (curChar == 60)
                     jjCheckNAddStates(48, 51);
                  else if (curChar == 10)
                     jjstateSet[jjnewStateCnt++] = 37;
                  else if (curChar == 58)
                     jjCheckNAdd(27);
                  else if (curChar == 37)
                     jjCheckNAdd(27);
                  else if (curChar == 42)
                     jjCheckNAdd(27);
                  else if (curChar == 33)
                     jjCheckNAdd(27);
                  else if (curChar == 61)
                     jjCheckNAdd(27);
                  break;
               case 37:
               case 0:
                  if ((0x100002600L & l) == 0L)
                     break;
                  if (kind > 5)
                     kind = 5;
                  jjCheckNAdd(0);
                  break;
               case 26:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 16)
                     kind = 16;
                  jjstateSet[jjnewStateCnt++] = 26;
                  break;
               case 27:
                  if (curChar == 61 && kind > 18)
                     kind = 18;
                  break;
               case 28:
                  if (curChar == 61)
                     jjCheckNAdd(27);
                  break;
               case 29:
                  if (curChar == 33)
                     jjCheckNAdd(27);
                  break;
               case 30:
                  if (curChar == 42)
                     jjCheckNAdd(27);
                  break;
               case 31:
                  if (curChar == 37)
                     jjCheckNAdd(27);
                  break;
               case 33:
                  if (curChar == 58)
                     jjCheckNAdd(27);
                  break;
               case 34:
                  if ((0x7400ac6200000000L & l) != 0L && kind > 18)
                     kind = 18;
                  break;
               case 35:
                  if ((0x800530000000000L & l) != 0L && kind > 19)
                     kind = 19;
                  break;
               case 36:
                  if (curChar == 10)
                     jjstateSet[jjnewStateCnt++] = 37;
                  break;
               case 38:
                  if (curChar == 39 && kind > 23)
                     kind = 23;
                  break;
               case 39:
                  if ((0x7L & l) != 0L && kind > 24)
                     kind = 24;
                  break;
               case 41:
                  if ((0xff000000000000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 42;
                  break;
               case 42:
                  if ((0xff000000000000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 43;
                  break;
               case 43:
                  if ((0xff000000000000L & l) != 0L)
                     jjCheckNAdd(44);
                  break;
               case 45:
                  if (curChar == 34 && kind > 23)
                     kind = 23;
                  break;
               case 47:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 48;
                  break;
               case 48:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAdd(44);
                  break;
               case 49:
                  if (curChar == 60)
                     jjCheckNAddStates(48, 51);
                  break;
               case 50:
                  if (curChar == 60 && kind > 18)
                     kind = 18;
                  break;
               case 51:
                  if (curChar == 60)
                     jjCheckNAdd(27);
                  break;
               case 52:
                  if (curChar == 45 && kind > 18)
                     kind = 18;
                  break;
               case 53:
                  if (curChar == 62)
                     jjCheckNAddStates(45, 47);
                  break;
               case 54:
                  if (curChar == 62 && kind > 18)
                     kind = 18;
                  break;
               case 55:
                  if (curChar == 62)
                     jjCheckNAdd(27);
                  break;
               case 56:
                  if (curChar == 38)
                     jjCheckNAddStates(41, 44);
                  break;
               case 57:
                  if (curChar == 38 && kind > 18)
                     kind = 18;
                  break;
               case 62:
                  if (curChar == 43)
                     jjCheckNAddTwoStates(27, 63);
                  break;
               case 63:
                  if (curChar == 43 && kind > 18)
                     kind = 18;
                  break;
               case 64:
                  if (curChar == 45)
                     jjCheckNAddTwoStates(27, 52);
                  break;
               case 143:
                  if (curChar == 47)
                     jjCheckNAddStates(38, 40);
                  break;
               case 144:
                  if (curChar == 47)
                     jjCheckNAddTwoStates(145, 146);
                  break;
               case 145:
                  if ((0xffffffffffffdbffL & l) != 0L)
                     jjCheckNAddTwoStates(145, 146);
                  break;
               case 146:
                  if ((0x2400L & l) != 0L && kind > 6)
                     kind = 6;
                  break;
               case 147:
                  if (curChar == 42)
                     jjCheckNAddTwoStates(148, 149);
                  break;
               case 148:
                  if ((0xfffffbffffffffffL & l) != 0L)
                     jjCheckNAddTwoStates(148, 149);
                  break;
               case 149:
                  if (curChar == 42)
                     jjCheckNAddStates(52, 54);
                  break;
               case 150:
                  if ((0xffff7fffffffffffL & l) != 0L)
                     jjCheckNAddStates(52, 54);
                  break;
               case 151:
                  if (curChar == 47)
                     jjstateSet[jjnewStateCnt++] = 152;
                  break;
               case 152:
                  if ((0xfffffbffffffffffL & l) != 0L)
                     jjCheckNAddStates(52, 54);
                  break;
               case 153:
                  if (curChar == 42)
                     jjstateSet[jjnewStateCnt++] = 154;
                  break;
               case 154:
                  if (curChar == 47 && kind > 7)
                     kind = 7;
                  break;
               case 155:
                  if ((0x3fe000000000000L & l) == 0L)
                     break;
                  if (kind > 9)
                     kind = 9;
                  jjCheckNAddStates(22, 25);
                  break;
               case 156:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 9)
                     kind = 9;
                  jjCheckNAdd(156);
                  break;
               case 157:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 10)
                     kind = 10;
                  jjCheckNAdd(157);
                  break;
               case 158:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddTwoStates(158, 159);
                  break;
               case 160:
                  if (curChar != 48)
                     break;
                  if (kind > 9)
                     kind = 9;
                  jjCheckNAddStates(28, 37);
                  break;
               case 162:
                  if ((0x3000000000000L & l) == 0L)
                     break;
                  if (kind > 9)
                     kind = 9;
                  jjstateSet[jjnewStateCnt++] = 162;
                  break;
               case 164:
                  if ((0xff000000000000L & l) == 0L)
                     break;
                  if (kind > 9)
                     kind = 9;
                  jjstateSet[jjnewStateCnt++] = 164;
                  break;
               case 166:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 9)
                     kind = 9;
                  jjstateSet[jjnewStateCnt++] = 166;
                  break;
               case 168:
                  if ((0x3000000000000L & l) == 0L)
                     break;
                  if (kind > 11)
                     kind = 11;
                  jjstateSet[jjnewStateCnt++] = 168;
                  break;
               case 170:
                  if ((0xff000000000000L & l) == 0L)
                     break;
                  if (kind > 12)
                     kind = 12;
                  jjstateSet[jjnewStateCnt++] = 170;
                  break;
               case 172:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 13)
                     kind = 13;
                  jjstateSet[jjnewStateCnt++] = 172;
                  break;
               case 174:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddTwoStates(174, 159);
                  break;
               case 176:
                  if ((0xff000000000000L & l) != 0L)
                     jjCheckNAddTwoStates(176, 159);
                  break;
               case 178:
                  if ((0x3000000000000L & l) != 0L)
                     jjCheckNAddTwoStates(178, 159);
                  break;
               case 179:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddStates(0, 11);
                  break;
               case 180:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddTwoStates(180, 181);
                  break;
               case 181:
                  if (curChar != 46)
                     break;
                  if (kind > 14)
                     kind = 14;
                  jjCheckNAddTwoStates(182, 183);
                  break;
               case 182:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 14)
                     kind = 14;
                  jjCheckNAddTwoStates(182, 183);
                  break;
               case 184:
                  if ((0x280000000000L & l) != 0L)
                     jjCheckNAdd(185);
                  break;
               case 185:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 14)
                     kind = 14;
                  jjCheckNAdd(185);
                  break;
               case 186:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddTwoStates(186, 187);
                  break;
               case 188:
                  if ((0x280000000000L & l) != 0L)
                     jjCheckNAdd(189);
                  break;
               case 189:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 14)
                     kind = 14;
                  jjCheckNAdd(189);
                  break;
               case 190:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddStates(55, 57);
                  break;
               case 193:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjAddStates(58, 59);
                  break;
               case 195:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddTwoStates(195, 196);
                  break;
               case 197:
                  if ((0x280000000000L & l) != 0L)
                     jjCheckNAdd(198);
                  break;
               case 198:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddTwoStates(198, 159);
                  break;
               case 199:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddTwoStates(199, 200);
                  break;
               case 200:
                  if (curChar == 46)
                     jjCheckNAddStates(60, 62);
                  break;
               case 201:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddStates(60, 62);
                  break;
               case 203:
                  if ((0x280000000000L & l) != 0L)
                     jjCheckNAdd(204);
                  break;
               case 204:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddTwoStates(204, 159);
                  break;
               case 205:
                  if (curChar != 43)
                     break;
                  if (kind > 17)
                     kind = 17;
                  jjstateSet[jjnewStateCnt++] = 206;
                  break;
               case 206:
                  if (curChar == 46)
                     jjstateSet[jjnewStateCnt++] = 207;
                  break;
               case 207:
                  if ((0x3ff000000000000L & l) != 0L && kind > 17)
                     kind = 17;
                  break;
               case 208:
                  if (curChar == 46)
                     jjAddStates(26, 27);
                  break;
               case 209:
                  if (curChar == 46 && kind > 18)
                     kind = 18;
                  break;
               case 210:
                  if (curChar == 46)
                     jjstateSet[jjnewStateCnt++] = 209;
                  break;
               case 211:
                  if (curChar == 46 && kind > 24)
                     kind = 24;
                  break;
               case 212:
                  if (curChar == 46)
                     jjstateSet[jjnewStateCnt++] = 211;
                  break;
               case 213:
                  if (curChar == 39)
                     jjAddStates(16, 21);
                  break;
               case 214:
                  if ((0x7L & l) != 0L)
                     jjCheckNAdd(215);
                  break;
               case 215:
                  if (curChar == 39 && kind > 20)
                     kind = 20;
                  break;
               case 216:
                  if (curChar == 46)
                     jjCheckNAdd(215);
                  break;
               case 217:
                  if (curChar == 46)
                     jjstateSet[jjnewStateCnt++] = 216;
                  break;
               case 218:
                  if (curChar == 46)
                     jjstateSet[jjnewStateCnt++] = 217;
                  break;
               case 220:
                  if ((0x8400000000L & l) != 0L)
                     jjCheckNAdd(221);
                  break;
               case 221:
                  if (curChar == 39 && kind > 21)
                     kind = 21;
                  break;
               case 222:
                  if ((0xffffff7fffffffffL & l) != 0L)
                     jjCheckNAdd(221);
                  break;
               case 224:
                  if ((0x7L & l) != 0L && kind > 23)
                     kind = 23;
                  break;
               case 225:
                  if (curChar == 46 && kind > 23)
                     kind = 23;
                  break;
               case 226:
               case 254:
                  if (curChar == 46)
                     jjCheckNAdd(225);
                  break;
               case 227:
                  if (curChar == 46)
                     jjstateSet[jjnewStateCnt++] = 226;
                  break;
               case 229:
                  if ((0x8400000000L & l) != 0L)
                     jjCheckNAdd(215);
                  break;
               case 231:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 232;
                  break;
               case 232:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 233;
                  break;
               case 233:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 234;
                  break;
               case 234:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 235;
                  break;
               case 235:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 236;
                  break;
               case 236:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 237;
                  break;
               case 237:
               case 242:
               case 244:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAdd(238);
                  break;
               case 238:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAdd(215);
                  break;
               case 240:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 241;
                  break;
               case 241:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 242;
                  break;
               case 245:
                  if ((0xff000000000000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 246;
                  break;
               case 246:
                  if ((0xff000000000000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 247;
                  break;
               case 247:
                  if ((0xff000000000000L & l) != 0L)
                     jjCheckNAdd(215);
                  break;
               case 248:
                  if (curChar == 34)
                     jjCheckNAddStates(12, 15);
                  break;
               case 249:
                  if ((0xfffffffbffffffffL & l) != 0L)
                     jjCheckNAddStates(63, 65);
                  break;
               case 251:
                  if ((0x8400000000L & l) != 0L)
                     jjCheckNAddStates(63, 65);
                  break;
               case 252:
                  if (curChar == 34 && kind > 22)
                     kind = 22;
                  break;
               case 255:
                  if (curChar == 46)
                     jjstateSet[jjnewStateCnt++] = 254;
                  break;
               case 258:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 259;
                  break;
               case 259:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 260;
                  break;
               case 260:
               case 269:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAdd(261);
                  break;
               case 261:
                  if ((0x3ff000000000000L & l) != 0L && kind > 23)
                     kind = 23;
                  break;
               case 263:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 264;
                  break;
               case 264:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 265;
                  break;
               case 265:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 266;
                  break;
               case 266:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 267;
                  break;
               case 267:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 268;
                  break;
               case 268:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 269;
                  break;
               case 270:
                  if ((0x8400000000L & l) != 0L && kind > 23)
                     kind = 23;
                  break;
               default : break;
            }
         } while(i != startsAt);
      }
      else if (curChar < 128)
      {
         long l = 1L << (curChar & 077);
         do
         {
            switch(jjstateSet[--i])
            {
               case 5:
                  if ((0x7fffffe87fffffeL & l) != 0L)
                  {
                     if (kind > 16)
                        kind = 16;
                     jjCheckNAdd(26);
                  }
                  else if ((0x2800000028000000L & l) != 0L)
                  {
                     if (kind > 19)
                        kind = 19;
                  }
                  else if ((0x1000000040000000L & l) != 0L)
                  {
                     if (kind > 18)
                        kind = 18;
                  }
                  else if (curChar == 92)
                     jjAddStates(66, 67);
                  if (curChar == 114)
                     jjAddStates(68, 69);
                  else if (curChar == 103)
                     jjCheckNAddTwoStates(132, 134);
                  else if (curChar == 99)
                     jjAddStates(70, 73);
                  else if (curChar == 115)
                     jjAddStates(74, 76);
                  else if (curChar == 105)
                     jjAddStates(77, 79);
                  else if (curChar == 102)
                     jjAddStates(80, 82);
                  else if (curChar == 100)
                     jjAddStates(83, 84);
                  else if (curChar == 124)
                     jjCheckNAddTwoStates(61, 27);
                  else if (curChar == 94)
                     jjCheckNAdd(27);
                  else if (curChar == 118)
                     jjstateSet[jjnewStateCnt++] = 23;
                  else if (curChar == 116)
                     jjstateSet[jjnewStateCnt++] = 20;
                  else if (curChar == 112)
                     jjstateSet[jjnewStateCnt++] = 17;
                  else if (curChar == 101)
                     jjstateSet[jjnewStateCnt++] = 11;
                  else if (curChar == 109)
                     jjstateSet[jjnewStateCnt++] = 7;
                  else if (curChar == 98)
                     jjstateSet[jjnewStateCnt++] = 4;
                  break;
               case 37:
                  if (curChar == 125)
                     jjstateSet[jjnewStateCnt++] = 38;
                  break;
               case 1:
                  if (curChar == 107 && kind > 8)
                     kind = 8;
                  break;
               case 2:
                  if (curChar == 97)
                     jjstateSet[jjnewStateCnt++] = 1;
                  break;
               case 3:
                  if (curChar == 101)
                     jjstateSet[jjnewStateCnt++] = 2;
                  break;
               case 4:
                  if (curChar == 114)
                     jjstateSet[jjnewStateCnt++] = 3;
                  break;
               case 6:
                  if (curChar == 112 && kind > 8)
                     kind = 8;
                  break;
               case 7:
                  if (curChar == 97)
                     jjstateSet[jjnewStateCnt++] = 6;
                  break;
               case 8:
                  if (curChar == 109)
                     jjstateSet[jjnewStateCnt++] = 7;
                  break;
               case 9:
                  if (curChar == 101 && kind > 8)
                     kind = 8;
                  break;
               case 10:
               case 117:
                  if (curChar == 115)
                     jjCheckNAdd(9);
                  break;
               case 11:
                  if (curChar == 108)
                     jjstateSet[jjnewStateCnt++] = 10;
                  break;
               case 12:
                  if (curChar == 101)
                     jjstateSet[jjnewStateCnt++] = 11;
                  break;
               case 13:
               case 136:
                  if (curChar == 103)
                     jjCheckNAdd(9);
                  break;
               case 14:
                  if (curChar == 97)
                     jjstateSet[jjnewStateCnt++] = 13;
                  break;
               case 15:
                  if (curChar == 107)
                     jjstateSet[jjnewStateCnt++] = 14;
                  break;
               case 16:
                  if (curChar == 99)
                     jjstateSet[jjnewStateCnt++] = 15;
                  break;
               case 17:
                  if (curChar == 97)
                     jjstateSet[jjnewStateCnt++] = 16;
                  break;
               case 18:
                  if (curChar == 112)
                     jjstateSet[jjnewStateCnt++] = 17;
                  break;
               case 19:
                  if (curChar == 112)
                     jjCheckNAdd(9);
                  break;
               case 20:
                  if (curChar == 121)
                     jjstateSet[jjnewStateCnt++] = 19;
                  break;
               case 21:
                  if (curChar == 116)
                     jjstateSet[jjnewStateCnt++] = 20;
                  break;
               case 22:
                  if (curChar == 114 && kind > 8)
                     kind = 8;
                  break;
               case 23:
                  if (curChar == 97)
                     jjCheckNAdd(22);
                  break;
               case 24:
                  if (curChar == 118)
                     jjstateSet[jjnewStateCnt++] = 23;
                  break;
               case 25:
               case 26:
                  if ((0x7fffffe87fffffeL & l) == 0L)
                     break;
                  if (kind > 16)
                     kind = 16;
                  jjCheckNAdd(26);
                  break;
               case 32:
               case 59:
                  if (curChar == 94)
                     jjCheckNAdd(27);
                  break;
               case 34:
                  if ((0x1000000040000000L & l) != 0L && kind > 18)
                     kind = 18;
                  break;
               case 35:
                  if ((0x2800000028000000L & l) != 0L && kind > 19)
                     kind = 19;
                  break;
               case 40:
                  if (curChar == 92)
                     jjAddStates(66, 67);
                  break;
               case 44:
                  if (curChar == 125)
                     jjstateSet[jjnewStateCnt++] = 45;
                  break;
               case 46:
                  if (curChar == 120)
                     jjstateSet[jjnewStateCnt++] = 47;
                  break;
               case 47:
                  if ((0x7e0000007eL & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 48;
                  break;
               case 48:
                  if ((0x7e0000007eL & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 44;
                  break;
               case 58:
                  if (curChar == 94 && kind > 18)
                     kind = 18;
                  break;
               case 60:
                  if (curChar == 124)
                     jjCheckNAddTwoStates(61, 27);
                  break;
               case 61:
                  if (curChar == 124 && kind > 18)
                     kind = 18;
                  break;
               case 65:
                  if (curChar == 100)
                     jjAddStates(83, 84);
                  break;
               case 66:
                  if (curChar == 116 && kind > 8)
                     kind = 8;
                  break;
               case 67:
                  if (curChar == 108)
                     jjCheckNAdd(66);
                  break;
               case 68:
                  if (curChar == 117)
                     jjstateSet[jjnewStateCnt++] = 67;
                  break;
               case 69:
                  if (curChar == 97)
                     jjstateSet[jjnewStateCnt++] = 68;
                  break;
               case 70:
                  if (curChar == 102)
                     jjstateSet[jjnewStateCnt++] = 69;
                  break;
               case 71:
                  if (curChar == 101)
                     jjstateSet[jjnewStateCnt++] = 70;
                  break;
               case 72:
                  if (curChar == 101)
                     jjCheckNAdd(22);
                  break;
               case 73:
                  if (curChar == 102)
                     jjstateSet[jjnewStateCnt++] = 72;
                  break;
               case 74:
                  if (curChar == 101)
                     jjstateSet[jjnewStateCnt++] = 73;
                  break;
               case 75:
                  if (curChar == 102)
                     jjAddStates(80, 82);
                  break;
               case 76:
                  if (curChar == 99 && kind > 8)
                     kind = 8;
                  break;
               case 77:
                  if (curChar == 110)
                     jjstateSet[jjnewStateCnt++] = 76;
                  break;
               case 78:
                  if (curChar == 117)
                     jjstateSet[jjnewStateCnt++] = 77;
                  break;
               case 79:
                  if (curChar == 104 && kind > 8)
                     kind = 8;
                  break;
               case 80:
                  if (curChar == 103)
                     jjCheckNAdd(79);
                  break;
               case 81:
                  if (curChar == 117)
                     jjstateSet[jjnewStateCnt++] = 80;
                  break;
               case 82:
                  if (curChar == 111)
                     jjstateSet[jjnewStateCnt++] = 81;
                  break;
               case 83:
                  if (curChar == 114)
                     jjstateSet[jjnewStateCnt++] = 82;
                  break;
               case 84:
                  if (curChar == 104)
                     jjstateSet[jjnewStateCnt++] = 83;
                  break;
               case 85:
                  if (curChar == 116)
                     jjstateSet[jjnewStateCnt++] = 84;
                  break;
               case 86:
                  if (curChar == 108)
                     jjstateSet[jjnewStateCnt++] = 85;
                  break;
               case 87:
                  if (curChar == 108)
                     jjstateSet[jjnewStateCnt++] = 86;
                  break;
               case 88:
                  if (curChar == 97)
                     jjstateSet[jjnewStateCnt++] = 87;
                  break;
               case 89:
                  if (curChar == 111)
                     jjCheckNAdd(22);
                  break;
               case 90:
                  if (curChar == 105)
                     jjAddStates(77, 79);
                  break;
               case 91:
                  if (curChar == 99)
                     jjCheckNAdd(9);
                  break;
               case 92:
                  if (curChar == 97)
                     jjstateSet[jjnewStateCnt++] = 91;
                  break;
               case 93:
                  if (curChar == 102)
                     jjstateSet[jjnewStateCnt++] = 92;
                  break;
               case 94:
                  if (curChar == 114)
                     jjstateSet[jjnewStateCnt++] = 93;
                  break;
               case 95:
                  if (curChar == 101)
                     jjstateSet[jjnewStateCnt++] = 94;
                  break;
               case 96:
                  if (curChar == 116)
                     jjstateSet[jjnewStateCnt++] = 95;
                  break;
               case 97:
                  if (curChar == 110)
                     jjstateSet[jjnewStateCnt++] = 96;
                  break;
               case 98:
                  if (curChar == 102 && kind > 8)
                     kind = 8;
                  break;
               case 99:
                  if (curChar == 114)
                     jjCheckNAdd(66);
                  break;
               case 100:
                  if (curChar == 111)
                     jjstateSet[jjnewStateCnt++] = 99;
                  break;
               case 101:
                  if (curChar == 112)
                     jjstateSet[jjnewStateCnt++] = 100;
                  break;
               case 102:
                  if (curChar == 109)
                     jjstateSet[jjnewStateCnt++] = 101;
                  break;
               case 103:
                  if (curChar == 115)
                     jjAddStates(74, 76);
                  break;
               case 104:
               case 108:
                  if (curChar == 99)
                     jjCheckNAdd(66);
                  break;
               case 105:
                  if (curChar == 101)
                     jjstateSet[jjnewStateCnt++] = 104;
                  break;
               case 106:
                  if (curChar == 108)
                     jjstateSet[jjnewStateCnt++] = 105;
                  break;
               case 107:
                  if (curChar == 101)
                     jjstateSet[jjnewStateCnt++] = 106;
                  break;
               case 109:
                  if (curChar == 117)
                     jjstateSet[jjnewStateCnt++] = 108;
                  break;
               case 110:
                  if (curChar == 114)
                     jjstateSet[jjnewStateCnt++] = 109;
                  break;
               case 111:
                  if (curChar == 116)
                     jjstateSet[jjnewStateCnt++] = 110;
                  break;
               case 112:
                  if (curChar == 99)
                     jjCheckNAdd(79);
                  break;
               case 113:
                  if (curChar == 116)
                     jjstateSet[jjnewStateCnt++] = 112;
                  break;
               case 114:
                  if (curChar == 105)
                     jjstateSet[jjnewStateCnt++] = 113;
                  break;
               case 115:
                  if (curChar == 119)
                     jjstateSet[jjnewStateCnt++] = 114;
                  break;
               case 116:
                  if (curChar == 99)
                     jjAddStates(70, 73);
                  break;
               case 118:
                  if (curChar == 97)
                     jjstateSet[jjnewStateCnt++] = 117;
                  break;
               case 119:
                  if (curChar == 110 && kind > 8)
                     kind = 8;
                  break;
               case 120:
                  if (curChar == 97)
                     jjCheckNAdd(119);
                  break;
               case 121:
                  if (curChar == 104)
                     jjstateSet[jjnewStateCnt++] = 120;
                  break;
               case 122:
                  if (curChar == 115)
                     jjCheckNAdd(66);
                  break;
               case 123:
                  if (curChar == 110)
                     jjstateSet[jjnewStateCnt++] = 122;
                  break;
               case 124:
                  if (curChar == 111)
                     jjstateSet[jjnewStateCnt++] = 123;
                  break;
               case 125:
                  if (curChar == 117)
                     jjCheckNAdd(9);
                  break;
               case 126:
                  if (curChar == 110)
                     jjstateSet[jjnewStateCnt++] = 125;
                  break;
               case 127:
                  if (curChar == 105)
                     jjstateSet[jjnewStateCnt++] = 126;
                  break;
               case 128:
                  if (curChar == 116)
                     jjstateSet[jjnewStateCnt++] = 127;
                  break;
               case 129:
                  if (curChar == 110)
                     jjstateSet[jjnewStateCnt++] = 128;
                  break;
               case 130:
                  if (curChar == 111)
                     jjstateSet[jjnewStateCnt++] = 129;
                  break;
               case 131:
                  if (curChar == 103)
                     jjCheckNAddTwoStates(132, 134);
                  break;
               case 132:
                  if (curChar == 111 && kind > 8)
                     kind = 8;
                  break;
               case 133:
                  if (curChar == 116)
                     jjCheckNAdd(132);
                  break;
               case 134:
                  if (curChar == 111)
                     jjstateSet[jjnewStateCnt++] = 133;
                  break;
               case 135:
                  if (curChar == 114)
                     jjAddStates(68, 69);
                  break;
               case 137:
                  if (curChar == 110)
                     jjstateSet[jjnewStateCnt++] = 136;
                  break;
               case 138:
                  if (curChar == 97)
                     jjstateSet[jjnewStateCnt++] = 137;
                  break;
               case 139:
                  if (curChar == 114)
                     jjCheckNAdd(119);
                  break;
               case 140:
                  if (curChar == 117)
                     jjstateSet[jjnewStateCnt++] = 139;
                  break;
               case 141:
                  if (curChar == 116)
                     jjstateSet[jjnewStateCnt++] = 140;
                  break;
               case 142:
                  if (curChar == 101)
                     jjstateSet[jjnewStateCnt++] = 141;
                  break;
               case 145:
                  jjAddStates(85, 86);
                  break;
               case 148:
                  jjAddStates(87, 88);
                  break;
               case 150:
               case 152:
                  jjCheckNAddStates(52, 54);
                  break;
               case 159:
                  if (curChar == 105 && kind > 15)
                     kind = 15;
                  break;
               case 161:
                  if ((0x400000004L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 162;
                  break;
               case 163:
                  if ((0x800000008000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 164;
                  break;
               case 165:
                  if ((0x100000001000000L & l) != 0L)
                     jjCheckNAdd(166);
                  break;
               case 166:
                  if ((0x7e0000007eL & l) == 0L)
                     break;
                  if (kind > 9)
                     kind = 9;
                  jjCheckNAdd(166);
                  break;
               case 167:
                  if ((0x400000004L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 168;
                  break;
               case 169:
                  if ((0x800000008000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 170;
                  break;
               case 171:
                  if ((0x100000001000000L & l) != 0L)
                     jjCheckNAdd(172);
                  break;
               case 172:
                  if ((0x7e0000007eL & l) == 0L)
                     break;
                  if (kind > 13)
                     kind = 13;
                  jjCheckNAdd(172);
                  break;
               case 173:
                  if ((0x100000001000000L & l) != 0L)
                     jjCheckNAdd(174);
                  break;
               case 174:
                  if ((0x7e0000007eL & l) != 0L)
                     jjCheckNAddTwoStates(174, 159);
                  break;
               case 175:
                  if ((0x800000008000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 176;
                  break;
               case 177:
                  if ((0x400000004L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 178;
                  break;
               case 183:
                  if ((0x2000000020L & l) != 0L)
                     jjAddStates(89, 90);
                  break;
               case 187:
                  if ((0x2000000020L & l) != 0L)
                     jjAddStates(91, 92);
                  break;
               case 191:
                  if (curChar == 123)
                     jjstateSet[jjnewStateCnt++] = 192;
                  break;
               case 192:
                  if (curChar == 95)
                     jjstateSet[jjnewStateCnt++] = 193;
                  break;
               case 194:
                  if (curChar == 125)
                     jjCheckNAddTwoStates(191, 159);
                  break;
               case 196:
                  if ((0x2000000020L & l) != 0L)
                     jjAddStates(93, 94);
                  break;
               case 202:
                  if ((0x2000000020L & l) != 0L)
                     jjAddStates(95, 96);
                  break;
               case 219:
                  if (curChar == 92)
                     jjstateSet[jjnewStateCnt++] = 220;
                  break;
               case 220:
                  if ((0x54404610000000L & l) != 0L)
                     jjCheckNAdd(221);
                  break;
               case 222:
                  if ((0xffffffffefffffffL & l) != 0L)
                     jjCheckNAdd(221);
                  break;
               case 223:
                  if (curChar == 123)
                     jjCheckNAddTwoStates(224, 227);
                  break;
               case 228:
                  if (curChar == 92)
                     jjAddStates(97, 101);
                  break;
               case 229:
                  if ((0x54404610000000L & l) != 0L)
                     jjCheckNAdd(215);
                  break;
               case 230:
                  if (curChar == 85)
                     jjstateSet[jjnewStateCnt++] = 231;
                  break;
               case 231:
                  if ((0x7e0000007eL & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 232;
                  break;
               case 232:
                  if ((0x7e0000007eL & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 233;
                  break;
               case 233:
                  if ((0x7e0000007eL & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 234;
                  break;
               case 234:
                  if ((0x7e0000007eL & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 235;
                  break;
               case 235:
                  if ((0x7e0000007eL & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 236;
                  break;
               case 236:
                  if ((0x7e0000007eL & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 237;
                  break;
               case 237:
               case 242:
               case 244:
                  if ((0x7e0000007eL & l) != 0L)
                     jjCheckNAdd(238);
                  break;
               case 238:
                  if ((0x7e0000007eL & l) != 0L)
                     jjCheckNAdd(215);
                  break;
               case 239:
                  if (curChar == 117)
                     jjstateSet[jjnewStateCnt++] = 240;
                  break;
               case 240:
                  if ((0x7e0000007eL & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 241;
                  break;
               case 241:
                  if ((0x7e0000007eL & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 242;
                  break;
               case 243:
                  if (curChar == 120)
                     jjstateSet[jjnewStateCnt++] = 244;
                  break;
               case 249:
                  if ((0xffffffffefffffffL & l) != 0L)
                     jjCheckNAddStates(63, 65);
                  break;
               case 250:
                  if (curChar == 92)
                     jjstateSet[jjnewStateCnt++] = 251;
                  break;
               case 251:
                  if ((0x54404610000000L & l) != 0L)
                     jjCheckNAddStates(63, 65);
                  break;
               case 253:
                  if (curChar == 123)
                     jjCheckNAddStates(102, 104);
                  break;
               case 256:
                  if (curChar == 92)
                     jjAddStates(105, 107);
                  break;
               case 257:
                  if (curChar == 117)
                     jjstateSet[jjnewStateCnt++] = 258;
                  break;
               case 258:
                  if ((0x7e0000007eL & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 259;
                  break;
               case 259:
                  if ((0x7e0000007eL & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 260;
                  break;
               case 260:
               case 269:
                  if ((0x7e0000007eL & l) != 0L)
                     jjCheckNAdd(261);
                  break;
               case 261:
                  if ((0x7e0000007eL & l) != 0L && kind > 23)
                     kind = 23;
                  break;
               case 262:
                  if (curChar == 85)
                     jjstateSet[jjnewStateCnt++] = 263;
                  break;
               case 263:
                  if ((0x7e0000007eL & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 264;
                  break;
               case 264:
                  if ((0x7e0000007eL & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 265;
                  break;
               case 265:
                  if ((0x7e0000007eL & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 266;
                  break;
               case 266:
                  if ((0x7e0000007eL & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 267;
                  break;
               case 267:
                  if ((0x7e0000007eL & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 268;
                  break;
               case 268:
                  if ((0x7e0000007eL & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 269;
                  break;
               case 270:
                  if ((0x54404610000000L & l) != 0L && kind > 23)
                     kind = 23;
                  break;
               default : break;
            }
         } while(i != startsAt);
      }
      else
      {
         int hiByte = (int)(curChar >> 8);
         int i1 = hiByte >> 6;
         long l1 = 1L << (hiByte & 077);
         int i2 = (curChar & 0xff) >> 6;
         long l2 = 1L << (curChar & 077);
         do
         {
            switch(jjstateSet[--i])
            {
               case 5:
                  if (jjCanMove_0(hiByte, i1, i2, l1, l2) && kind > 24)
                     kind = 24;
                  break;
               case 145:
                  if (jjCanMove_1(hiByte, i1, i2, l1, l2))
                     jjAddStates(85, 86);
                  break;
               case 148:
                  if (jjCanMove_1(hiByte, i1, i2, l1, l2))
                     jjAddStates(87, 88);
                  break;
               case 150:
               case 152:
                  if (jjCanMove_1(hiByte, i1, i2, l1, l2))
                     jjCheckNAddStates(52, 54);
                  break;
               case 214:
                  if (jjCanMove_0(hiByte, i1, i2, l1, l2))
                     jjstateSet[jjnewStateCnt++] = 215;
                  break;
               case 222:
                  if (jjCanMove_2(hiByte, i1, i2, l1, l2))
                     jjstateSet[jjnewStateCnt++] = 221;
                  break;
               case 224:
                  if (jjCanMove_0(hiByte, i1, i2, l1, l2) && kind > 23)
                     kind = 23;
                  break;
               case 249:
                  if (jjCanMove_2(hiByte, i1, i2, l1, l2))
                     jjAddStates(63, 65);
                  break;
               default : break;
            }
         } while(i != startsAt);
      }
      if (kind != 0x7fffffff)
      {
         jjmatchedKind = kind;
         jjmatchedPos = curPos;
         kind = 0x7fffffff;
      }
      ++curPos;
      if ((i = jjnewStateCnt) == (startsAt = 271 - (jjnewStateCnt = startsAt)))
         return curPos;
      try { curChar = input_stream.readChar(); }
      catch(java.io.IOException e) { return curPos; }
   }
}
static final int[] jjnextStates = {
   180, 181, 186, 187, 190, 191, 195, 196, 199, 200, 159, 205, 249, 250, 252, 253, 
   214, 218, 219, 222, 223, 228, 156, 157, 158, 159, 210, 212, 161, 163, 165, 167, 
   169, 171, 173, 175, 177, 159, 144, 147, 27, 57, 58, 27, 59, 27, 54, 55, 
   27, 50, 51, 52, 150, 151, 153, 190, 191, 159, 193, 194, 201, 202, 159, 249, 
   250, 252, 41, 46, 138, 142, 118, 121, 124, 130, 107, 111, 115, 97, 98, 102, 
   78, 88, 89, 71, 74, 145, 146, 148, 149, 184, 185, 188, 189, 197, 198, 203, 
   204, 229, 230, 239, 243, 245, 255, 224, 256, 257, 262, 270, 
};
private static final boolean jjCanMove_0(int hiByte, int i1, int i2, long l1, long l2)
{
   switch(hiByte)
   {
      case 255:
         return ((jjbitVec0[i2] & l2) != 0L);
      default : 
         return false;
   }
}
private static final boolean jjCanMove_1(int hiByte, int i1, int i2, long l1, long l2)
{
   switch(hiByte)
   {
      case 0:
         return ((jjbitVec1[i2] & l2) != 0L);
      default : 
         return false;
   }
}
private static final boolean jjCanMove_2(int hiByte, int i1, int i2, long l1, long l2)
{
   switch(hiByte)
   {
      case 0:
         return ((jjbitVec1[i2] & l2) != 0L);
      default : 
         if ((jjbitVec2[i1] & l1) != 0L)
            return true;
         return false;
   }
}

/** Token literal values. */
public static final String[] jjstrLiteralImages = {
null, null, null, null, null, null, null, null, null, null, null, null, null, 
null, null, null, null, null, null, null, null, null, null, null, null, null, null, 
null, null, null, null, null, null, null, null, null, null, null, null, null, null, 
null, null, null, null, null, null, null, null, null, };

/** Lexer state names. */
public static final String[] lexStateNames = {
   "DEFAULT", 
};
static final long[] jjtoToken = {
   0x1ffff01L, 
};
static final long[] jjtoSkip = {
   0x1eL, 
};
static final long[] jjtoMore = {
   0xe0L, 
};
static protected SimpleCharStream input_stream;
static private final int[] jjrounds = new int[271];
static private final int[] jjstateSet = new int[542];
static protected char curChar;
/** Constructor. */
public GoTokenManager(SimpleCharStream stream){
   if (input_stream != null)
      throw new TokenMgrError("ERROR: Second call to constructor of static lexer. You must use ReInit() to initialize the static variables.", TokenMgrError.STATIC_LEXER_ERROR);
   input_stream = stream;
}

/** Constructor. */
public GoTokenManager(SimpleCharStream stream, int lexState){
   this(stream);
   SwitchTo(lexState);
}

/** Reinitialise parser. */
static public void ReInit(SimpleCharStream stream)
{
   jjmatchedPos = jjnewStateCnt = 0;
   curLexState = defaultLexState;
   input_stream = stream;
   ReInitRounds();
}
static private void ReInitRounds()
{
   int i;
   jjround = 0x80000001;
   for (i = 271; i-- > 0;)
      jjrounds[i] = 0x80000000;
}

/** Reinitialise parser. */
static public void ReInit(SimpleCharStream stream, int lexState)
{
   ReInit(stream);
   SwitchTo(lexState);
}

/** Switch to specified lex state. */
static public void SwitchTo(int lexState)
{
   if (lexState >= 1 || lexState < 0)
      throw new TokenMgrError("Error: Ignoring invalid lexical state : " + lexState + ". State unchanged.", TokenMgrError.INVALID_LEXICAL_STATE);
   else
      curLexState = lexState;
}

static protected Token jjFillToken()
{
   final Token t;
   final String tokenImage;
   final int beginLine;
   final int endLine;
   final int beginColumn;
   final int endColumn;
   String im = jjstrLiteralImages[jjmatchedKind];
   tokenImage = (im == null) ? input_stream.GetImage() : im;
   beginLine = input_stream.getBeginLine();
   beginColumn = input_stream.getBeginColumn();
   endLine = input_stream.getEndLine();
   endColumn = input_stream.getEndColumn();
   t = Token.newToken(jjmatchedKind, tokenImage);

   t.beginLine = beginLine;
   t.endLine = endLine;
   t.beginColumn = beginColumn;
   t.endColumn = endColumn;

   return t;
}

static int curLexState = 0;
static int defaultLexState = 0;
static int jjnewStateCnt;
static int jjround;
static int jjmatchedPos;
static int jjmatchedKind;

/** Get the next Token. */
public static Token getNextToken() 
{
  //int kind;
  Token specialToken = null;
  Token matchedToken;
  int curPos = 0;

  EOFLoop :
  for (;;)
  {   
   try   
   {     
      curChar = input_stream.BeginToken();
   }     
   catch(java.io.IOException e)
   {        
      jjmatchedKind = 0;
      matchedToken = jjFillToken();
      return matchedToken;
   }

   for (;;)
   {
     jjmatchedKind = 0x7fffffff;
     jjmatchedPos = 0;
     curPos = jjMoveStringLiteralDfa0_0();
   if (jjmatchedKind != 0x7fffffff)
   {
      if (jjmatchedPos + 1 < curPos)
         input_stream.backup(curPos - jjmatchedPos - 1);
      if ((jjtoToken[jjmatchedKind >> 6] & (1L << (jjmatchedKind & 077))) != 0L)
      {
         matchedToken = jjFillToken();
         return matchedToken;
      }
      else if ((jjtoSkip[jjmatchedKind >> 6] & (1L << (jjmatchedKind & 077))) != 0L)
      {
         continue EOFLoop;
      }
      curPos = 0;
      jjmatchedKind = 0x7fffffff;
      try {
         curChar = input_stream.readChar();
         continue;
      }
      catch (java.io.IOException e1) { }
   }
   int error_line = input_stream.getEndLine();
   int error_column = input_stream.getEndColumn();
   String error_after = null;
   boolean EOFSeen = false;
   try { input_stream.readChar(); input_stream.backup(1); }
   catch (java.io.IOException e1) {
      EOFSeen = true;
      error_after = curPos <= 1 ? "" : input_stream.GetImage();
      if (curChar == '\n' || curChar == '\r') {
         error_line++;
         error_column = 0;
      }
      else
         error_column++;
   }
   if (!EOFSeen) {
      input_stream.backup(1);
      error_after = curPos <= 1 ? "" : input_stream.GetImage();
   }
   throw new TokenMgrError(EOFSeen, curLexState, error_line, error_column, error_after, curChar, TokenMgrError.LEXICAL_ERROR);
 }
  }
}

static private void jjCheckNAdd(int state)
{
   if (jjrounds[state] != jjround)
   {
      jjstateSet[jjnewStateCnt++] = state;
      jjrounds[state] = jjround;
   }
}
static private void jjAddStates(int start, int end)
{
   do {
      jjstateSet[jjnewStateCnt++] = jjnextStates[start];
   } while (start++ != end);
}
static private void jjCheckNAddTwoStates(int state1, int state2)
{
   jjCheckNAdd(state1);
   jjCheckNAdd(state2);
}

static private void jjCheckNAddStates(int start, int end)
{
   do {
      jjCheckNAdd(jjnextStates[start]);
   } while (start++ != end);
}

}
